package main

import (
	"flag"
	"log"
	"strings"

	"github.com/jirfag/go-queryset/queryset"
)

func main() {
	inFile := flag.String("in", "models.go", "path to input file")
	outFile := flag.String("out", "autogenerated_{in}", "path to output file")
	flag.Parse()

	*outFile = strings.Replace(*outFile, "{in}", *inFile, 1)
	if err := queryset.GenerateQuerySets(*inFile, *outFile); err != nil {
		log.Fatalf("can't generate query sets: %s", err)
	}
}
