test_static:
	gometalinter --vendor --enable-all --min-confidence=0.3 --line-length=120 \
		-e "parameter \w+ always receives" \
		-e "/jinzhu/gorm/" \
		-e "model is unused" \
		-e '"expections" is a misspelling of "exceptions"' \
		-e "autogenerated_" \
		--deadline=5m \
		./...

test_unit:
	mkdir -p test
	go test -v ./parser/ ./queryset/ ./queryset/methods/

AUTOGEN_FILES = \
	./queryset/test/autogenerated_models.go \
	./examples/comparison/gorm4/autogenerated_gorm4.go \
	./queryset/test/pkgimport/autogenerated_models.go

test_gen: gen
	@- $(foreach F,$(AUTOGEN_FILES), \
		go build $$(dirname $F)/*.go; \
	)

test: test_unit bench test_static test_gen

bench:
	go test -bench=. -benchtime=1s -v -run=^$$ ./queryset/

gen:
	@- $(foreach F,$(AUTOGEN_FILES), \
		go generate $$(dirname $F); \
	)
