package test

import (
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
	"github.com/jirfag/go-queryset/queryset/tmp"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set BlogQuerySet

// BlogQuerySet is an queryset type for Blog
type BlogQuerySet struct {
	db *gorm.DB
}

// NewBlogQuerySet constructs new BlogQuerySet
func NewBlogQuerySet(db *gorm.DB) BlogQuerySet {
	return BlogQuerySet{
		db: db,
	}
}

// All is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) All(ret *[]Blog) error {
	return qs.db.Find(ret).Error
}

// Create is an autogenerated method
// nolint: dupl
func (o *Blog) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtEq(createdAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at = ?", createdAt)
	})
	return qs
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtGt(createdAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at > ?", createdAt)
	})
	return qs
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtGte(createdAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at >= ?", createdAt)
	})
	return qs
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtLt(createdAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at < ?", createdAt)
	})
	return qs
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtLte(createdAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at <= ?", createdAt)
	})
	return qs
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtNe(createdAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at != ?", createdAt)
	})
	return qs
}

// Delete is an autogenerated method
// nolint: dupl
func (o *Blog) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) Delete() error {
	return qs.db.Delete(Blog{}).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtEq(deletedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at = ?", deletedAt)
	})
	return qs
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtGt(deletedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at > ?", deletedAt)
	})
	return qs
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtGte(deletedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at >= ?", deletedAt)
	})
	return qs
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtIsNull() BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at IS NULL")
	})
	return qs
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtLt(deletedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at < ?", deletedAt)
	})
	return qs
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtLte(deletedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at <= ?", deletedAt)
	})
	return qs
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeletedAtNe(deletedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at != ?", deletedAt)
	})
	return qs
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) GetUpdater() BlogUpdater {
	return NewBlogUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDEq(ID uint) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id = ?", ID)
	})
	return qs
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDGt(ID uint) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id > ?", ID)
	})
	return qs
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDGte(ID uint) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id >= ?", ID)
	})
	return qs
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDLt(ID uint) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id < ?", ID)
	})
	return qs
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDLte(ID uint) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id <= ?", ID)
	})
	return qs
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDNe(ID uint) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id != ?", ID)
	})
	return qs
}

// Limit is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) Limit(limit int) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Limit(limit)
	})
	return qs
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameEq(name string) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("name = ?", name)
	})
	return qs
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameNe(name string) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("name != ?", name)
	})
	return qs
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs BlogQuerySet) One(ret *Blog) error {
	return qs.db.First(ret).Error
}

// OrderByCreatedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderByCreatedAt() BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("created_at")
	})
	return qs
}

// OrderByDeletedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderByDeletedAt() BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("deleted_at")
	})
	return qs
}

// OrderByID is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderByID() BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("id")
	})
	return qs
}

// OrderByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderByUpdatedAt() BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("updated_at")
	})
	return qs
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetCreatedAt(createdAt time.Time) BlogUpdater {
	u.fields[string(BlogDBSchema.CreatedAt)] = createdAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetID(ID uint) BlogUpdater {
	u.fields[string(BlogDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetName(name string) BlogUpdater {
	u.fields[string(BlogDBSchema.Name)] = name
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetUpdatedAt(updatedAt time.Time) BlogUpdater {
	u.fields[string(BlogDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u BlogUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtEq(updatedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at = ?", updatedAt)
	})
	return qs
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtGt(updatedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at > ?", updatedAt)
	})
	return qs
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtGte(updatedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at >= ?", updatedAt)
	})
	return qs
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtLt(updatedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at < ?", updatedAt)
	})
	return qs
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtLte(updatedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at <= ?", updatedAt)
	})
	return qs
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtNe(updatedAt time.Time) BlogQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at != ?", updatedAt)
	})
	return qs
}

// ===== END of query set BlogQuerySet

// ===== BEGIN of Blog modifiers

type blogDBSchemaField string

// BlogDBSchema stores db field names of Blog
var BlogDBSchema = struct {
	ID        blogDBSchemaField
	CreatedAt blogDBSchemaField
	UpdatedAt blogDBSchemaField
	DeletedAt blogDBSchemaField
	Name      blogDBSchemaField
}{

	ID:        blogDBSchemaField("id"),
	CreatedAt: blogDBSchemaField("created_at"),
	UpdatedAt: blogDBSchemaField("updated_at"),
	DeletedAt: blogDBSchemaField("deleted_at"),
	Name:      blogDBSchemaField("name"),
}

// Update updates Blog fields by primary key
func (o *Blog) Update(db *gorm.DB, fields ...blogDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"created_at": o.CreatedAt,
		"updated_at": o.UpdatedAt,
		"deleted_at": o.DeletedAt,
		"name":       o.Name,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := string(f)
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update Blog %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// BlogUpdater is an Blog updates manager
type BlogUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewBlogUpdater creates new Blog updater
func NewBlogUpdater(db *gorm.DB) BlogUpdater {
	return BlogUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&Blog{}),
	}
}

// ===== END of Blog modifiers

// ===== BEGIN of query set PostQuerySet

// PostQuerySet is an queryset type for Post
type PostQuerySet struct {
	db *gorm.DB
}

// NewPostQuerySet constructs new PostQuerySet
func NewPostQuerySet(db *gorm.DB) PostQuerySet {
	return PostQuerySet{
		db: db,
	}
}

// All is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) All(ret *[]Post) error {
	return qs.db.Find(ret).Error
}

// BlogIsNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) BlogIsNull() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("blog IS NULL")
	})
	return qs
}

// Create is an autogenerated method
// nolint: dupl
func (o *Post) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtEq(createdAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at = ?", createdAt)
	})
	return qs
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtGt(createdAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at > ?", createdAt)
	})
	return qs
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtGte(createdAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at >= ?", createdAt)
	})
	return qs
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtLt(createdAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at < ?", createdAt)
	})
	return qs
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtLte(createdAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at <= ?", createdAt)
	})
	return qs
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtNe(createdAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at != ?", createdAt)
	})
	return qs
}

// Delete is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) Delete() error {
	return qs.db.Delete(Post{}).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *Post) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtEq(deletedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at = ?", deletedAt)
	})
	return qs
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtGt(deletedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at > ?", deletedAt)
	})
	return qs
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtGte(deletedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at >= ?", deletedAt)
	})
	return qs
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtIsNull() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at IS NULL")
	})
	return qs
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtLt(deletedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at < ?", deletedAt)
	})
	return qs
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtLte(deletedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at <= ?", deletedAt)
	})
	return qs
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeletedAtNe(deletedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at != ?", deletedAt)
	})
	return qs
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) GetUpdater() PostUpdater {
	return NewPostUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDEq(ID uint) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id = ?", ID)
	})
	return qs
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDGt(ID uint) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id > ?", ID)
	})
	return qs
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDGte(ID uint) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id >= ?", ID)
	})
	return qs
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDLt(ID uint) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id < ?", ID)
	})
	return qs
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDLte(ID uint) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id <= ?", ID)
	})
	return qs
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDNe(ID uint) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id != ?", ID)
	})
	return qs
}

// Limit is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) Limit(limit int) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Limit(limit)
	})
	return qs
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs PostQuerySet) One(ret *Post) error {
	return qs.db.First(ret).Error
}

// OrderByCreatedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderByCreatedAt() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("created_at")
	})
	return qs
}

// OrderByDeletedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderByDeletedAt() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("deleted_at")
	})
	return qs
}

// OrderByID is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderByID() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("id")
	})
	return qs
}

// OrderByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderByUpdatedAt() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("updated_at")
	})
	return qs
}

// PreloadBlog is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) PreloadBlog() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Preload("Blog")
	})
	return qs
}

// PreloadUser is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) PreloadUser() PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Preload("User")
	})
	return qs
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetCreatedAt(createdAt time.Time) PostUpdater {
	u.fields[string(PostDBSchema.CreatedAt)] = createdAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetID(ID uint) PostUpdater {
	u.fields[string(PostDBSchema.ID)] = ID
	return u
}

// SetStr is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetStr(str tmp.StringDef) PostUpdater {
	u.fields[string(PostDBSchema.Str)] = str
	return u
}

// SetTitle is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetTitle(title string) PostUpdater {
	u.fields[string(PostDBSchema.Title)] = title
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetUpdatedAt(updatedAt time.Time) PostUpdater {
	u.fields[string(PostDBSchema.UpdatedAt)] = updatedAt
	return u
}

// SetUser is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetUser(user User) PostUpdater {
	u.fields[string(PostDBSchema.User)] = user
	return u
}

// StrEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrEq(str tmp.StringDef) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("str = ?", str)
	})
	return qs
}

// StrNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrNe(str tmp.StringDef) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("str != ?", str)
	})
	return qs
}

// TitleEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleEq(title string) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("title = ?", title)
	})
	return qs
}

// TitleNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleNe(title string) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("title != ?", title)
	})
	return qs
}

// Update is an autogenerated method
// nolint: dupl
func (u PostUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtEq(updatedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at = ?", updatedAt)
	})
	return qs
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtGt(updatedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at > ?", updatedAt)
	})
	return qs
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtGte(updatedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at >= ?", updatedAt)
	})
	return qs
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtLt(updatedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at < ?", updatedAt)
	})
	return qs
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtLte(updatedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at <= ?", updatedAt)
	})
	return qs
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtNe(updatedAt time.Time) PostQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at != ?", updatedAt)
	})
	return qs
}

// ===== END of query set PostQuerySet

// ===== BEGIN of Post modifiers

type postDBSchemaField string

// PostDBSchema stores db field names of Post
var PostDBSchema = struct {
	ID        postDBSchemaField
	CreatedAt postDBSchemaField
	UpdatedAt postDBSchemaField
	DeletedAt postDBSchemaField
	Blog      postDBSchemaField
	User      postDBSchemaField
	Title     postDBSchemaField
	Str       postDBSchemaField
}{

	ID:        postDBSchemaField("id"),
	CreatedAt: postDBSchemaField("created_at"),
	UpdatedAt: postDBSchemaField("updated_at"),
	DeletedAt: postDBSchemaField("deleted_at"),
	Blog:      postDBSchemaField("blog"),
	User:      postDBSchemaField("user"),
	Title:     postDBSchemaField("title"),
	Str:       postDBSchemaField("str"),
}

// Update updates Post fields by primary key
func (o *Post) Update(db *gorm.DB, fields ...postDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"created_at": o.CreatedAt,
		"updated_at": o.UpdatedAt,
		"deleted_at": o.DeletedAt,
		"blog":       o.Blog,
		"user":       o.User,
		"title":      o.Title,
		"str":        o.Str,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := string(f)
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update Post %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// PostUpdater is an Post updates manager
type PostUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewPostUpdater creates new Post updater
func NewPostUpdater(db *gorm.DB) PostUpdater {
	return PostUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&Post{}),
	}
}

// ===== END of Post modifiers

// ===== BEGIN of query set UserQuerySet

// UserQuerySet is an queryset type for User
type UserQuerySet struct {
	db *gorm.DB
}

// NewUserQuerySet constructs new UserQuerySet
func NewUserQuerySet(db *gorm.DB) UserQuerySet {
	return UserQuerySet{
		db: db,
	}
}

// All is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) All(ret *[]User) error {
	return qs.db.Find(ret).Error
}

// Create is an autogenerated method
// nolint: dupl
func (o *User) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtEq(createdAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at = ?", createdAt)
	})
	return qs
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtGt(createdAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at > ?", createdAt)
	})
	return qs
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtGte(createdAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at >= ?", createdAt)
	})
	return qs
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtLt(createdAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at < ?", createdAt)
	})
	return qs
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtLte(createdAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at <= ?", createdAt)
	})
	return qs
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtNe(createdAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("created_at != ?", createdAt)
	})
	return qs
}

// Delete is an autogenerated method
// nolint: dupl
func (o *User) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Delete() error {
	return qs.db.Delete(User{}).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtEq(deletedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at = ?", deletedAt)
	})
	return qs
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtGt(deletedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at > ?", deletedAt)
	})
	return qs
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtGte(deletedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at >= ?", deletedAt)
	})
	return qs
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtIsNull() UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at IS NULL")
	})
	return qs
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtLt(deletedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at < ?", deletedAt)
	})
	return qs
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtLte(deletedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at <= ?", deletedAt)
	})
	return qs
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeletedAtNe(deletedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("deleted_at != ?", deletedAt)
	})
	return qs
}

// EmailEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailEq(email string) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("email = ?", email)
	})
	return qs
}

// EmailNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNe(email string) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("email != ?", email)
	})
	return qs
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) GetUpdater() UserUpdater {
	return NewUserUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDEq(ID uint) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id = ?", ID)
	})
	return qs
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDGt(ID uint) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id > ?", ID)
	})
	return qs
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDGte(ID uint) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id >= ?", ID)
	})
	return qs
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDLt(ID uint) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id < ?", ID)
	})
	return qs
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDLte(ID uint) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id <= ?", ID)
	})
	return qs
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDNe(ID uint) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("id != ?", ID)
	})
	return qs
}

// Limit is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Limit(limit int) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Limit(limit)
	})
	return qs
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameEq(name string) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("name = ?", name)
	})
	return qs
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameNe(name string) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("name != ?", name)
	})
	return qs
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs UserQuerySet) One(ret *User) error {
	return qs.db.First(ret).Error
}

// OrderByCreatedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderByCreatedAt() UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("created_at")
	})
	return qs
}

// OrderByDeletedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderByDeletedAt() UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("deleted_at")
	})
	return qs
}

// OrderByID is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderByID() UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("id")
	})
	return qs
}

// OrderByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderByUpdatedAt() UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Order("updated_at")
	})
	return qs
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetCreatedAt(createdAt time.Time) UserUpdater {
	u.fields[string(UserDBSchema.CreatedAt)] = createdAt
	return u
}

// SetEmail is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetEmail(email string) UserUpdater {
	u.fields[string(UserDBSchema.Email)] = email
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetID(ID uint) UserUpdater {
	u.fields[string(UserDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetName(name string) UserUpdater {
	u.fields[string(UserDBSchema.Name)] = name
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetUpdatedAt(updatedAt time.Time) UserUpdater {
	u.fields[string(UserDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u UserUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtEq(updatedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at = ?", updatedAt)
	})
	return qs
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtGt(updatedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at > ?", updatedAt)
	})
	return qs
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtGte(updatedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at >= ?", updatedAt)
	})
	return qs
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtLt(updatedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at < ?", updatedAt)
	})
	return qs
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtLte(updatedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at <= ?", updatedAt)
	})
	return qs
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtNe(updatedAt time.Time) UserQuerySet {
	qs.db = qs.db.Scopes(func(d *gorm.DB) *gorm.DB {
		return d.Where("updated_at != ?", updatedAt)
	})
	return qs
}

// ===== END of query set UserQuerySet

// ===== BEGIN of User modifiers

type userDBSchemaField string

// UserDBSchema stores db field names of User
var UserDBSchema = struct {
	ID        userDBSchemaField
	CreatedAt userDBSchemaField
	UpdatedAt userDBSchemaField
	DeletedAt userDBSchemaField
	Name      userDBSchemaField
	Email     userDBSchemaField
}{

	ID:        userDBSchemaField("id"),
	CreatedAt: userDBSchemaField("created_at"),
	UpdatedAt: userDBSchemaField("updated_at"),
	DeletedAt: userDBSchemaField("deleted_at"),
	Name:      userDBSchemaField("name"),
	Email:     userDBSchemaField("email"),
}

// Update updates User fields by primary key
func (o *User) Update(db *gorm.DB, fields ...userDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"created_at": o.CreatedAt,
		"updated_at": o.UpdatedAt,
		"deleted_at": o.DeletedAt,
		"name":       o.Name,
		"email":      o.Email,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := string(f)
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update User %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// UserUpdater is an User updates manager
type UserUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewUserUpdater creates new User updater
func NewUserUpdater(db *gorm.DB) UserUpdater {
	return UserUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&User{}),
	}
}

// ===== END of User modifiers

// ===== END of all query sets
