package test

//go:generate go run ../../main.go -in models.go -out autogenerated_queryset.go

type Model struct {
	ID int
	//DeletedAt, UpdatedAt time.Time
}

// User is a usual user
// gen:qs
type User struct {
	Model

	//Posts []Post
	Name string
}

// Blog is a blog
// gen:qs
type Blog struct {
	Model

	Name string
}

// Post is an article
// gen:qs
type Post struct {
	Model

	Blog  *Blog // may be no blog
	User  User
	Title string
}
