package test

//go:generate go run ../../main.go -in models.go -out autogenerated_queryset.go

// Model is needed only for embedding testing
type Model struct {
	ID int
	//DeletedAt, UpdatedAt time.Time
}

// User is a usual user
// gen:qs
type User struct {
	Model

	//Posts []Post
	Name string
}

// Blog is a blog
// gen:qs
type Blog struct {
	Model

	Name string
}

// Post is an article
// gen:qs
type Post struct {
	Model

	Blog  *Blog // may be no blog
	User  User
	Title string
}

// String is just for testing purposes
func (p *Post) String() string {
	return ""
}

// SomeMethod is just for testing purposes
func (b *Blog) SomeMethod() string {
	if b.ID%2 == 0 {
		return "1"
	}

	return "0"
}
